### ISSUE TITLE
Contact Required

### ISSUE THREAD

**Issue by Aikatsui** [malhuda2/megaableadmin#1]
Hi Alhuda,

The email address mentioned on blog ADMIN@MALHUDA.COM is unreachable then i decided to open an issue on your one of repo. Can you provide correct email address or other IM contact? 

Good day

**Comment by malhuda** [comment]
You can contact me again at email admin@malhuda.com , email activated after maintenance

**Comment by Aikatsui** [comment]
@malhuda2 Did you received a mail yesterday mention about DNS servers?
